"""add status to user

Revision ID: bd7e2b399d41
Revises: 1f06bfdb8285
Create Date: 2025-06-01 17:02:11.815446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7e2b399d41'
down_revision = '1f06bfdb8285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspension_ends_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('suspension_ends_at')

    # ### end Alembic commands ###
